name: gameroom_app
description: An app for playing a variety of turn-based games with friends.

version: 1.0.0+1

sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  json_serializable: ^3.2.0
  web_socket_channel: ^1.1.0
  mockito: ^4.1.1
  stomp: ^0.8.0
  dartdoc: ^0.30.2
  provider: ^4.0.5
  recase: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0


flutter:
  assets:
    - assets/
    - assets/chess/
    - assets/checkers/
    - assets/tic-tac-toe/
  uses-material-design: true

